version: 0
metadata:
  name: firefox devtools
  description: ''
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.synchronize
          - push
    payload:
      maxRunTime: 3600
      image: rail/python-test-runner
      command: 
        - "/bin/bash"
        - "-cx"
        - >
          mkdir -p /home/worker/artifacts/public/ &&
          apt-get install -y sshpass p7zip-full xvfb git python-pip libgtk-3-0 &&
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git checkout {{event.head.sha}} &&
          pip install --upgrade pip &&
          source config.sh &&
          export DISPLAY=":99.0" &&
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -nolisten tcp -screen 0 1600x1200x24 &&
          export SHA={{event.head.sha}} &&
          echo $SHA &&
          ./scripts/build-xpi.sh &&
          mv devtools.xpi /home/worker/artifacts/public/ &&
          export MOZ_UPLOAD_DIR=/home/worker/artifacts/public/ &&
          ./test.sh --quiet --screenshot-on-fail client/framework/ 2>&1 | tee logs &&
          mv logs /home/worker/artifacts/public/
      artifacts:
        'public':
          type: 'directory'
          path: '/home/worker/artifacts/public/'
          
    metadata:
      name: Build devtools add-on
      description: ''
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'

